@apiURL = https://vaenerbc-csc-rahti-docker-workflow-git-vaenerbc-rahti-projekt-1.2.rahtiapp.fi/rooms

### Get all products
GET {{apiURL}}

### Get One Product
GET {{apiURL}}/

### Create new product
POST {{apiURL}}
Content-Type: application/json

{

}

### Updatera product info (Patch)
# PUT uppdaterar allt
PUT {{apiURL}}/
Content-Type: application/json

{

}
### Update product info
# Patch updaterar enskillda saker
PATCH {{apiURL}}/
Content-Type: application/json

{
   
}



### Delete all products
DELETE {{apiURL}}/